feat: 챌린지 리스트 UI 업데이트 & props 정리
Jak-Sim/client-web pull request #7
Opened 2024-12-05 13:50 UTC by dusunax

### UI 업데이트 (디자인 반영)
- "진행 중인 챌린지" 텍스트 추가
- 채팅 리스트 placeholder
![image](https://github.com/user-attachments/assets/86a014df-2729-4e01-a6c2-f24879468b16)

### props 정리
- 노션의 response 예시를 기반으로 props의 challenge와 컴포넌트 내 출력 로직을 수정했습니다.

2024-12-06 02:06 UTC, Changsoon-Yun requested changes

2024-12-06 02:06 UTC, Changsoon-Yun commented on src/app/(pages)/challenge/_components/ChallengeCard.tsx
> +  const { data: session } = useSession();
useSession보단 page.tsx단에서 getServerSession으로 바로 유저정보 가져오고 props로 내려주는게 어떨까 싶어요 번거롭긴 하지만..

useSession은 클라이언트에서만 돌다보니까 loading이나 authenticated같은 status를 갖고있어서 유저가 보기에 아~~주 잠깐이지만 깜빡일 수 있겠다고 생각이 되고 

만약에 unAuth 유저라면 page단이나 list컴포넌트에서 선제적으로 걸러줄 redirect 로직이나 ui같은걸 바로 보여줄 수 있는게 장점이라고 생각합니다

참고) https://next-auth.js.org/getting-started/client
useSession, getSession(getServerSession권장)

2024-12-06 02:06 UTC, Changsoon-Yun commented on src/app/(pages)/challenge/_components/ChallengeList.tsx
> +      {challengeList.map((challenge: Challenge) => (
저는 ts에서 추론이 되는것들은 굳이 명시는 안하는편이긴 한데 어떤쪽으로 통일할까요? 제가 명시를 할까요? 아니면 그냥 개인 취향으로 둘까요? 사실 저보다 ts컴파일러가 똑똑해서 제가명시하면 틀리다고함 ㅋㅋ

2024-12-06 03:40 UTC, dusunax commented on src/app/(pages)/challenge/_components/ChallengeList.tsx
> +      {challengeList.map((challenge: Challenge) => (
타입 추론으로 통일하죠!

2024-12-06 04:06 UTC, dusunax commented on src/app/(pages)/challenge/_components/ChallengeCard.tsx
> +  const { data: session } = useSession();
넵 좋은 생각인 것 같아요
page단에 pagegetServerSession 적용했습니다. 👉 https://github.com/Jak-Sim/client-web/pull/7/commits/795e4bde57d58aef83e9cdcb6ae354e322dd9d3e

다만 지금 서버가 켜져 있지 않아서 session null인 경우를 지금 거르면 곤란하기 때문에
이번 PR에서는 이렇게 작성했어요

https://github.com/Jak-Sim/client-web/blob/795e4bde57d58aef83e9cdcb6ae354e322dd9d3e/src/app/(pages)/challenge/code/page.tsx#L7-L14

2024-12-07 04:23 UTC, Changsoon-Yun approved these changes

2024-12-07 04:43 UTC, merged